# ForgeOS captive portal DHCP/DNS
interface=wlan0
except-interface=lo
bind-interfaces

dhcp-range=192.168.4.10,192.168.4.250,255.255.255.0,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
dhcp-authoritative

# Captive: todo DNS cai no portal
no-resolv
no-hosts
address=/#/192.168.4.1
