blank_issues_enabled: false
contact_links:
  - name: Forge Forums
    url: https://forum.Forge.com/
    about: For general questions and community support, please visit the Forge Forums
  - name: Documentation
    url: https://docs.Forge.com/
    about: Check the official Forge documentation for guides and FAQs
